### PR TITLE
Install the latest version of `pip`

### PR DESCRIPTION
**Pull request by rmartin16**
## Changes
- Given that a distro provided `pip` may be quite old, install the latest `pip` inside the image
- To accommodate [PEP 668](https://peps.python.org/pep-0668/), the latest `pip` is installed using `PIP_BREAK_SYSTEM_PACKAGES=1`
- Update Toga and Pygame tests so they use the local repo for CI instead of downloading the current one
- Aligned the `pyproject.toml` configs for the test apps with current `briefcase-template`

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
hmm...this isn't working on `debian:bookworm`...

```
Docker| #8 [5/5] RUN python3 -m pip install --user --upgrade pip
Docker| #8 0.388 error: externally-managed-environment
Docker| #8 0.388 
Docker| #8 0.388 × This environment is externally managed
Docker| #8 0.388 ╰─> To install Python packages system-wide, try apt install
Docker| #8 0.388     python3-xyz, where xyz is the package you are trying to
Docker| #8 0.388     install.
Docker| #8 0.388     
Docker| #8 0.388     If you wish to install a non-Debian-packaged Python package,
Docker| #8 0.388     create a virtual environment using python3 -m venv path/to/venv.
Docker| #8 0.388     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
Docker| #8 0.388     sure you have python3-full installed.
Docker| #8 0.388     
Docker| #8 0.388     If you wish to install a non-Debian packaged Python application,
Docker| #8 0.388     it may be easiest to use pipx install xyz, which will manage a
Docker| #8 0.388     virtual environment for you. Make sure you have pipx installed.
Docker| #8 0.388     
Docker| #8 0.388     See /usr/share/doc/python3.11/README.venv for more information.
Docker| #8 0.388 
Docker| #8 0.388 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
Docker| #8 0.388 hint: See PEP 668 for the detailed specification.
Docker| #8 ERROR: process "/bin/sh -c python3 -m pip install --user --upgrade pip" did not complete successfully: exit code: 1
Docker| ------
Docker|  > [5/5] RUN python3 -m pip install --user --upgrade pip:
Docker| #8 0.388     sure you have python3-full installed.
Docker| #8 0.388     
Docker| #8 0.388     If you wish to install a non-Debian packaged Python application,
Docker| #8 0.388     it may be easiest to use pipx install xyz, which will manage a
Docker| #8 0.388     virtual environment for you. Make sure you have pipx installed.
Docker| #8 0.388     
Docker| #8 0.388     See /usr/share/doc/python3.11/README.venv for more information.
Docker| #8 0.388 
Docker| #8 0.388 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
Docker| #8 0.388 hint: See PEP 668 for the detailed specification.
Docker| ------
Docker| Dockerfile:29
Docker| --------------------
Docker|   27 |     
Docker|   28 |     # Install latest pip for user
Docker|   29 | >>> RUN python3 -m pip install --user --upgrade pip
Docker|   30 |     
Docker|   31 |     # ========== START USER PROVIDED CONTENT ==========
Docker| --------------------
Docker| ERROR: failed to solve: process "/bin/sh -c python3 -m pip install --user --upgrade pip" did not complete successfully: exit code: 1
```

**Comment by rmartin16** [comment]
See Point 5 in [Use Cases](https://peps.python.org/pep-0668/#use-cases) of PEP 668 for the discussion of containers.

This is a bit more than I wanted to bite off here....so, I'll wait for feedback at this point.

**Comment by freakboy3742** [comment]
/me waves fist at Debian...

I don't see how we can do anything other than use `--break-system-packages` here. The broader Python ecosystem essentially *expects* a recent version of pip to exist; Debian believes in baking versions until the end of time. We're stuck in the middle - but we can't do what we need to do without an updated version of pip. 

The positive side to this is that we're installing updating pip inside a very purpose-built docker container - we need up an updated version of pip for *our* usage, but that won't impact on the end user's environment.  We just need it to get python packages our app's environment, which will be largely isolated from the system, except for the actual Python standard library (of which pip isn't part).

I'm also not sure about the use of a virtual environment here, for much the same reason. When building a system package, we're deliberately *not* using a virtual environment, because we want to use the raw system Python (or, at least, the libPython and standard library). Using a venv seems like a level of abstraction that is either (a) not provide any actual protection, but at a complexity cost, or (b) introduce some subtle re-write that causes a package to break at runtime because it thinks it is located in a virtual environment that doesn't exist at runtime.

**Comment by rmartin16** [comment]
That's makes sense. I added `PIP_BREAK_SYSTEM_PACKAGES` to bypass the "externally managed python" error.

In practice, I doubt a virtual environment would lead to issues...but it's definitely totally unnecessary and really _only_ serves a potential source of issues. I removed it.

I was also curious how distros respond to upgrading `pip` for the system Python. As it turns out, no one _actually_ upgrades `pip` where the distro installed it. Rather, a new version of `pip` shadows the distro `pip` such that the new version is found during ambiguous invocation of `pip`.

`debian:bookworm`
```
Docker| #8 [5/5] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #8 0.234 pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
Docker| #8 0.445 Requirement already satisfied: pip in /usr/lib/python3/dist-packages (23.0.1)
Docker| #8 0.604 Collecting pip
Docker| #8 0.734   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #8 0.929      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 10.9 MB/s eta 0:00:00
Docker| #8 0.942 Installing collected packages: pip
Docker| #8 0.942   Attempting uninstall: pip
Docker| #8 0.944     Found existing installation: pip 23.0.1
Docker| #8 0.944     Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Docker| #8 0.944     Can't uninstall 'pip'. No files were found to uninstall.
Docker| #8 1.545 Successfully installed pip-23.2.1
Docker| #8 1.724 pip 23.2.1 from /usr/local/lib/python3.11/dist-packages/pip (python 3.11)
```

`debian:bullseye`
```
Docker| #8 [5/5] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #8 0.630 pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
Docker| #8 1.220 Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.3.4)
Docker| #8 1.454 Collecting pip
Docker| #8 1.567   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #8 1.752 Installing collected packages: pip
Docker| #8 1.752   Attempting uninstall: pip
Docker| #8 1.752     Found existing installation: pip 20.3.4
Docker| #8 1.752     Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Docker| #8 1.752     Can't uninstall 'pip'. No files were found to uninstall.
Docker| #8 2.303 Successfully installed pip-23.2.1
Docker| #8 2.473 pip 23.2.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
```

`ubuntu:lunar`
```
Docker| #8 [5/5] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #8 0.332 pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
Docker| #8 0.545 Requirement already satisfied: pip in /usr/lib/python3/dist-packages (23.0.1)
Docker| #8 0.699 Collecting pip
Docker| #8 0.823   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #8 1.307      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.3 MB/s eta 0:00:00
Docker| #8 1.324 Installing collected packages: pip
Docker| #8 1.324   Attempting uninstall: pip
Docker| #8 1.326     Found existing installation: pip 23.0.1
Docker| #8 1.326     Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Docker| #8 1.327     Can't uninstall 'pip'. No files were found to uninstall.
Docker| #8 2.000 Successfully installed pip-23.2.1
Docker| #8 2.227 pip 23.2.1 from /usr/local/lib/python3.11/dist-packages/pip (python 3.11)
```

`ubuntu:focal`
```
Docker| #8 [5/5] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #8 0.611 pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
Docker| #8 1.449 Collecting pip
Docker| #8 1.561   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #8 1.893 Installing collected packages: pip
Docker| #8 1.893   Attempting uninstall: pip
Docker| #8 1.893     Found existing installation: pip 20.0.2
Docker| #8 1.897     Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Docker| #8 1.897     Can't uninstall 'pip'. No files were found to uninstall.
Docker| #8 2.629 Successfully installed pip-23.2.1
Docker| #8 2.827 pip 23.2.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

`fedora:38`
```
Docker| #8 [5/5] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #8 0.337 pip 22.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
Docker| #8 0.565 Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (22.3.1)
Docker| #8 0.717 Collecting pip
Docker| #8 0.843   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #8 1.046      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 10.4 MB/s eta 0:00:00
Docker| #8 1.104 Installing collected packages: pip
Docker| #8 1.738 Successfully installed pip-23.2.1
Docker| #8 2.108 pip 23.2.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
```

`fedora:35`
```
Docker| #9 [6/6] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #9 0.571 pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)
Docker| #9 0.776 Defaulting to user installation because normal site-packages is not writeable
Docker| #9 0.784 Requirement already satisfied: pip in /usr/lib/python3.10/site-packages (21.2.3)
Docker| #9 1.976 Collecting pip
Docker| #9 3.104   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #9 9.392 Installing collected packages: pip
Docker| #9 10.06 Successfully installed pip-23.2.1
Docker| #9 10.76 pip 23.2.1 from /home/brutus/.local/lib/python3.10/site-packages/pip (python 3.10)
```

`archlinux`
```
Docker| #10 [7/7] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #10 0.514 pip 22.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
Docker| #10 0.705 Defaulting to user installation because normal site-packages is not writeable
Docker| #10 0.734 Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (22.3.1)
Docker| #10 1.088 Collecting pip
Docker| #10 1.384   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #10 2.936      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.3 MB/s eta 0:00:00
Docker| #10 2.970 Installing collected packages: pip
Docker| #10 3.573 Successfully installed pip-23.2.1
Docker| #10 4.173 
Docker| #10 4.173 [notice] A new release of pip available: 22.3.1 -> 23.2.1
Docker| #10 4.173 [notice] To update, run: pip3 install --upgrade pip
Docker| #10 4.366 pip 23.2.1 from /home/brutus/.local/lib/python3.11/site-packages/pip (python 3.11)
```

`manjarolinux/base`
```
Docker| #10 [7/7] RUN python3 -m pip -V && python3 -m pip install --upgrade pip && python3 -m pip -V
Docker| #10 0.652 pip 22.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
Docker| #10 0.864 Defaulting to user installation because normal site-packages is not writeable
Docker| #10 0.925 Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (22.3.1)
Docker| #10 1.060 Collecting pip
Docker| #10 1.166   Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
Docker| #10 1.414      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.4 MB/s eta 0:00:00
Docker| #10 1.520 Installing collected packages: pip
Docker| #10 2.130 Successfully installed pip-23.2.1
Docker| #10 2.278 
Docker| #10 2.278 [notice] A new release of pip available: 22.3.1 -> 23.2.1
Docker| #10 2.278 [notice] To update, run: pip3 install --upgrade pip
Docker| #10 2.467 pip 23.2.1 from /builder/.local/lib/python3.11/site-packages/pip (python 3.11)
```

**Comment by rmartin16** [comment]
Should we also consider upgrading `setuptools`? and even `wheel` for that matter? Otherwise, we'll be using whatever comes with the distro to install the packages for the app.

**Comment by freakboy3742** [comment]
> Should we also consider upgrading `setuptools`? and even `wheel` for that matter? Otherwise, we'll be using whatever comes with the distro to install the packages for the app.

I'd agree that both of these should be updated. Anything in the Briefcase "not upper pinned" is probably a candidate for this; in practice, pip, setuptools and wheel are probably the only ones we care about.

**Comment by rmartin16** [comment]
Good deal; upgrading `setuptools` and `wheel` with `pip`. and there's a few other optimizations.

**Review by freakboy3742 — APPROVED** [review]
This all looks solid 👍

**Pull request merged**
